module P = struct
  type el = string

  let german_names =
    [| {js|Albrecht|js}
     ; {js|Arnold|js}
     ; {js|Bauer|js}
     ; {js|Baumann|js}
     ; {js|Becker|js}
     ; {js|Beck|js}
     ; {js|Berger|js}
     ; {js|Bergmann|js}
     ; {js|Brandt|js}
     ; {js|Braun|js}
     ; {js|Busch|js}
     ; {js|Böhm|js}
     ; {js|Dietrich|js}
     ; {js|Engel|js}
     ; {js|Fischer|js}
     ; {js|Franke|js}
     ; {js|Frank|js}
     ; {js|Friedrich|js}
     ; {js|Fuchs|js}
     ; {js|Graf|js}
     ; {js|Groß|js}
     ; {js|Günther|js}
     ; {js|Haas|js}
     ; {js|Hahn|js}
     ; {js|Hartmann|js}
     ; {js|Heinrich|js}
     ; {js|Herrmann|js}
     ; {js|Hoffmann|js}
     ; {js|Hofmann|js}
     ; {js|Horn|js}
     ; {js|Huber|js}
     ; {js|Jung|js}
     ; {js|Jäger|js}
     ; {js|Kaiser|js}
     ; {js|Keller|js}
     ; {js|Klein|js}
     ; {js|Koch|js}
     ; {js|Krause|js}
     ; {js|Kraus|js}
     ; {js|Krämer|js}
     ; {js|Krüger|js}
     ; {js|Kuhn|js}
     ; {js|Köhler|js}
     ; {js|König|js}
     ; {js|Kühn|js}
     ; {js|Lange|js}
     ; {js|Lang|js}
     ; {js|Lehmann|js}
     ; {js|Lorenz|js}
     ; {js|Ludwig|js}
     ; {js|Maier|js}
     ; {js|Martin|js}
     ; {js|Mayer|js}
     ; {js|Meier|js}
     ; {js|Meyer|js}
     ; {js|Möller|js}
     ; {js|Müller|js}
     ; {js|Neumann|js}
     ; {js|Otto|js}
     ; {js|Peters|js}
     ; {js|Pfeiffer|js}
     ; {js|Pohl|js}
     ; {js|Richter|js}
     ; {js|Roth|js}
     ; {js|Sauer|js}
     ; {js|Schmidt|js}
     ; {js|Schmid|js}
     ; {js|Schmitt|js}
     ; {js|Schmitz|js}
     ; {js|Schneider|js}
     ; {js|Scholz|js}
     ; {js|Schreiber|js}
     ; {js|Schröder|js}
     ; {js|Schubert|js}
     ; {js|Schulte|js}
     ; {js|Schulze|js}
     ; {js|Schulz|js}
     ; {js|Schumacher|js}
     ; {js|Schuster|js}
     ; {js|Schwarz|js}
     ; {js|Schäfer|js}
     ; {js|Seidel|js}
     ; {js|Simon|js}
     ; {js|Sommer|js}
     ; {js|Stein|js}
     ; {js|Thomas|js}
     ; {js|Vogel|js}
     ; {js|Vogt|js}
     ; {js|Voigt|js}
     ; {js|Wagner|js}
     ; {js|Walter|js}
     ; {js|Weber|js}
     ; {js|Weiß|js}
     ; {js|Werner|js}
     ; {js|Winkler|js}
     ; {js|Winter|js}
     ; {js|Wolff|js}
     ; {js|Wolf|js}
     ; {js|Ziegler|js}
     ; {js|Zimmermann|js} |]

  let french_names =
    [| {js|Adam|js}
     ; {js|Andre|js}
     ; {js|Antoine|js}
     ; {js|Arnaud|js}
     ; {js|Aubert|js}
     ; {js|Aubry|js}
     ; {js|Bailly|js}
     ; {js|Barbier|js}
     ; {js|Baron|js}
     ; {js|Barre|js}
     ; {js|Barthelemy|js}
     ; {js|Benard|js}
     ; {js|Benoit|js}
     ; {js|Berger|js}
     ; {js|Bernard|js}
     ; {js|Bertin|js}
     ; {js|Bertrand|js}
     ; {js|Besson|js}
     ; {js|Blanchard|js}
     ; {js|Blanc|js}
     ; {js|Bonnet|js}
     ; {js|Boucher|js}
     ; {js|Bouchet|js}
     ; {js|Boulanger|js}
     ; {js|Bourgeois|js}
     ; {js|Bouvier|js}
     ; {js|Boyer|js}
     ; {js|Breton|js}
     ; {js|Brunet|js}
     ; {js|Brun|js}
     ; {js|Carlier|js}
     ; {js|Caron|js}
     ; {js|Carpentier|js}
     ; {js|Carre|js}
     ; {js|Charles|js}
     ; {js|Charpentier|js}
     ; {js|Chauvin|js}
     ; {js|Chevalier|js}
     ; {js|Chevallier|js}
     ; {js|Clement|js}
     ; {js|Colin|js}
     ; {js|Collet|js}
     ; {js|Collin|js}
     ; {js|Cordier|js}
     ; {js|Cousin|js}
     ; {js|Daniel|js}
     ; {js|David|js}
     ; {js|Da Silva|js}
     ; {js|Delaunay|js}
     ; {js|Denis|js}
     ; {js|Deschamps|js}
     ; {js|Dubois|js}
     ; {js|Dufour|js}
     ; {js|Dumas|js}
     ; {js|Dumont|js}
     ; {js|Dupont|js}
     ; {js|Dupuis|js}
     ; {js|Dupuy|js}
     ; {js|Durand|js}
     ; {js|Duval|js}
     ; {js|Etienne|js}
     ; {js|Fabre|js}
     ; {js|Faure|js}
     ; {js|Fernandez|js}
     ; {js|Fleury|js}
     ; {js|Fontaine|js}
     ; {js|Fournier|js}
     ; {js|Francois|js}
     ; {js|Gaillard|js}
     ; {js|Garcia|js}
     ; {js|Garnier|js}
     ; {js|Gauthier|js}
     ; {js|Gautier|js}
     ; {js|Gay|js}
     ; {js|Gerard|js}
     ; {js|Germain|js}
     ; {js|Gilbert|js}
     ; {js|Gillet|js}
     ; {js|Girard|js}
     ; {js|Giraud|js}
     ; {js|Grondin|js}
     ; {js|Guerin|js}
     ; {js|Guichard|js}
     ; {js|Guillaume|js}
     ; {js|Guillot|js}
     ; {js|Guyot|js}
     ; {js|Hamon|js}
     ; {js|Henry|js}
     ; {js|Herve|js}
     ; {js|Hoarau|js}
     ; {js|Hubert|js}
     ; {js|Huet|js}
     ; {js|Humbert|js}
     ; {js|Jacob|js}
     ; {js|Jacquet|js}
     ; {js|Jean|js}
     ; {js|Joly|js}
     ; {js|Julien|js}
     ; {js|Klein|js}
     ; {js|Lacroix|js}
     ; {js|Lambert|js}
     ; {js|Lamy|js}
     ; {js|Langlois|js}
     ; {js|Laporte|js}
     ; {js|Laurent|js}
     ; {js|Le Gall|js}
     ; {js|Le Goff|js}
     ; {js|Le Roux|js}
     ; {js|Leblanc|js}
     ; {js|Lebrun|js}
     ; {js|Leclercq|js}
     ; {js|Leclerc|js}
     ; {js|Lecomte|js}
     ; {js|Lefebvre|js}
     ; {js|Lefevre|js}
     ; {js|Leger|js}
     ; {js|Legrand|js}
     ; {js|Lejeune|js}
     ; {js|Lemaire|js}
     ; {js|Lemaitre|js}
     ; {js|Lemoine|js}
     ; {js|Leroux|js}
     ; {js|Leroy|js}
     ; {js|Leveque|js}
     ; {js|Lopez|js}
     ; {js|Louis|js}
     ; {js|Lucas|js}
     ; {js|Maillard|js}
     ; {js|Mallet|js}
     ; {js|Marchal|js}
     ; {js|Marchand|js}
     ; {js|Marechal|js}
     ; {js|Marie|js}
     ; {js|Martinez|js}
     ; {js|Martin|js}
     ; {js|Marty|js}
     ; {js|Masson|js}
     ; {js|Mathieu|js}
     ; {js|Menard|js}
     ; {js|Mercier|js}
     ; {js|Meunier|js}
     ; {js|Meyer|js}
     ; {js|Michaud|js}
     ; {js|Michel|js}
     ; {js|Millet|js}
     ; {js|Monnier|js}
     ; {js|Moreau|js}
     ; {js|Morel|js}
     ; {js|Morin|js}
     ; {js|Moulin|js}
     ; {js|Muller|js}
     ; {js|Nicolas|js}
     ; {js|Noel|js}
     ; {js|Olivier|js}
     ; {js|Paris|js}
     ; {js|Pasquier|js}
     ; {js|Payet|js}
     ; {js|Pelletier|js}
     ; {js|Perez|js}
     ; {js|Perret|js}
     ; {js|Perrier|js}
     ; {js|Perrin|js}
     ; {js|Perrot|js}
     ; {js|Petit|js}
     ; {js|Philippe|js}
     ; {js|Picard|js}
     ; {js|Pichon|js}
     ; {js|Pierre|js}
     ; {js|Poirier|js}
     ; {js|Poulain|js}
     ; {js|Prevost|js}
     ; {js|Remy|js}
     ; {js|Renard|js}
     ; {js|Renaud|js}
     ; {js|Renault|js}
     ; {js|Reynaud|js}
     ; {js|Rey|js}
     ; {js|Richard|js}
     ; {js|Riviere|js}
     ; {js|Robert|js}
     ; {js|Robin|js}
     ; {js|Roche|js}
     ; {js|Rodriguez|js}
     ; {js|Roger|js}
     ; {js|Rolland|js}
     ; {js|Rousseau|js}
     ; {js|Roussel|js}
     ; {js|Roux|js}
     ; {js|Royer|js}
     ; {js|Roy|js}
     ; {js|Sanchez|js}
     ; {js|Schmitt|js}
     ; {js|Schneider|js}
     ; {js|Simon|js}
     ; {js|Tessier|js}
     ; {js|Thomas|js}
     ; {js|Vasseur|js}
     ; {js|Vidal|js}
     ; {js|Vincent|js}
     ; {js|Weber|js} |]

  let elements = Js.Array2.concat french_names german_names
end

include Random_collection.Make (P)
