module P = struct
  type el = string

  let german_females =
    [| {js|Alina|js}
     ; {js|Anna|js}
     ; {js|Anne|js}
     ; {js|Annika|js}
     ; {js|Antonia|js}
     ; {js|Aylin|js}
     ; {js|Carolin|js}
     ; {js|Celina|js}
     ; {js|Christina|js}
     ; {js|Hannah|js}
     ; {js|Isabell|js}
     ; {js|Jacqueline|js}
     ; {js|Jana|js}
     ; {js|Janina|js}
     ; {js|Jennifer|js}
     ; {js|Jessika|js}
     ; {js|Johanna|js}
     ; {js|Julia|js}
     ; {js|Katharina|js}
     ; {js|Kim|js}
     ; {js|Laura|js}
     ; {js|Lea|js}
     ; {js|Lena|js}
     ; {js|Leonie|js}
     ; {js|Lisa|js}
     ; {js|Luisa|js}
     ; {js|Marie|js}
     ; {js|Michelle|js}
     ; {js|Natalie|js}
     ; {js|Nele|js}
     ; {js|Nina|js}
     ; {js|Sara|js}
     ; {js|Sofie|js}
     ; {js|Vanessa|js}
     ; {js|Yasmin|js} |]

  let german_males =
    [| {js|Alexander|js}
     ; {js|Daniel|js}
     ; {js|David|js}
     ; {js|Dennis|js}
     ; {js|Fabian|js}
     ; {js|Felix|js}
     ; {js|Finn|js}
     ; {js|Florian|js}
     ; {js|Jannik|js}
     ; {js|Jan|js}
     ; {js|Jonas|js}
     ; {js|Julian|js}
     ; {js|Kevin|js}
     ; {js|Lars|js}
     ; {js|Lennard|js}
     ; {js|Leon|js}
     ; {js|Lukas|js}
     ; {js|Marcel|js}
     ; {js|Mark|js}
     ; {js|Marvin|js}
     ; {js|Maximilian|js}
     ; {js|Max|js}
     ; {js|Moritz|js}
     ; {js|Niels|js}
     ; {js|Niklas|js}
     ; {js|Niko|js}
     ; {js|Pascal|js}
     ; {js|Paul|js}
     ; {js|Philipp|js}
     ; {js|Sebastian|js}
     ; {js|Simon|js}
     ; {js|Timo|js}
     ; {js|Tim|js}
     ; {js|Tobias|js}
     ; {js|Tom|js} |]

  let french_females =
    [| {js|Adeline|js}
     ; {js|Agathe|js}
     ; {js|Alexandra|js}
     ; {js|Alexia|js}
     ; {js|Alice|js}
     ; {js|Alicia|js}
     ; {js|Alison|js}
     ; {js|Amandine|js}
     ; {js|Amélie|js}
     ; {js|Anaïs|js}
     ; {js|Andréa|js}
     ; {js|Angelique|js}
     ; {js|Audrey|js}
     ; {js|Aurore|js}
     ; {js|Aurélie|js}
     ; {js|Axelle|js}
     ; {js|Camille|js}
     ; {js|Carla|js}
     ; {js|Caroline|js}
     ; {js|Cassandra|js}
     ; {js|Charline|js}
     ; {js|Charlotte|js}
     ; {js|Charlène|js}
     ; {js|Chloé|js}
     ; {js|Cindy|js}
     ; {js|Claire|js}
     ; {js|Clara|js}
     ; {js|Clémence|js}
     ; {js|Clémentine|js}
     ; {js|Coline|js}
     ; {js|Coralie|js}
     ; {js|Cynthia|js}
     ; {js|Cécile|js}
     ; {js|Célia|js}
     ; {js|Céline|js}
     ; {js|Deborah|js}
     ; {js|Elisa|js}
     ; {js|Elise|js}
     ; {js|Elodie|js}
     ; {js|Eloise|js}
     ; {js|Emeline|js}
     ; {js|Emilie|js}
     ; {js|Emma|js}
     ; {js|Estelle|js}
     ; {js|Eva|js}
     ; {js|Fanny|js}
     ; {js|Floriane|js}
     ; {js|Gaelle|js}
     ; {js|Gwendoline|js}
     ; {js|Inès|js}
     ; {js|Jade|js}
     ; {js|Jeanne|js}
     ; {js|Jennifer|js}
     ; {js|Jessica|js}
     ; {js|Johanna|js}
     ; {js|Julia|js}
     ; {js|Julie|js}
     ; {js|Juliette|js}
     ; {js|Justine|js}
     ; {js|Kelly|js}
     ; {js|Laetitia|js}
     ; {js|Laura|js}
     ; {js|Laure|js}
     ; {js|Laurie|js}
     ; {js|Laurine|js}
     ; {js|Lisa|js}
     ; {js|Louise|js}
     ; {js|Lucie|js}
     ; {js|Lucile|js}
     ; {js|Ludivine|js}
     ; {js|Léa|js}
     ; {js|Maeva|js}
     ; {js|Manon|js}
     ; {js|Margaux|js}
     ; {js|Margot|js}
     ; {js|Marie|js}
     ; {js|Marina|js}
     ; {js|Marine|js}
     ; {js|Marion|js}
     ; {js|Mathilde|js}
     ; {js|Megane|js}
     ; {js|Morgane|js}
     ; {js|Myriam|js}
     ; {js|Mélanie|js}
     ; {js|Mélissa|js}
     ; {js|Noemie|js}
     ; {js|Océane|js}
     ; {js|Ophélie|js}
     ; {js|Pauline|js}
     ; {js|Romane|js}
     ; {js|Sabrina|js}
     ; {js|Salomé|js}
     ; {js|Sandra|js}
     ; {js|Sarah|js}
     ; {js|Solène|js}
     ; {js|Sophie|js}
     ; {js|Stéphanie|js}
     ; {js|Tiffany|js}
     ; {js|Valentine|js}
     ; {js|Victoria|js} |]

  let french_males =
    [| {js|Adrien|js}
     ; {js|Alexandre|js}
     ; {js|Alexis|js}
     ; {js|Alex|js}
     ; {js|Anthony|js}
     ; {js|Antoine|js}
     ; {js|Arnaud|js}
     ; {js|Arthur|js}
     ; {js|Aurélien|js}
     ; {js|Axel|js}
     ; {js|Aymeric|js}
     ; {js|Baptiste|js}
     ; {js|Bastien|js}
     ; {js|Benjamin|js}
     ; {js|Benoît|js}
     ; {js|Brandon|js}
     ; {js|Bryan|js}
     ; {js|Cedric|js}
     ; {js|Charles|js}
     ; {js|Christopher|js}
     ; {js|Christophe|js}
     ; {js|Clément|js}
     ; {js|Corentin|js}
     ; {js|Cyril|js}
     ; {js|Damien|js}
     ; {js|David|js}
     ; {js|Dimitri|js}
     ; {js|Dorian|js}
     ; {js|Dylan|js}
     ; {js|Enzo|js}
     ; {js|Erwan|js}
     ; {js|Etienne|js}
     ; {js|Fabien|js}
     ; {js|Florent|js}
     ; {js|Florian|js}
     ; {js|François|js}
     ; {js|Gabriel|js}
     ; {js|Gaëtan|js}
     ; {js|Geoffrey|js}
     ; {js|Gregory|js}
     ; {js|Guillaume|js}
     ; {js|Hugo|js}
     ; {js|Jason|js}
     ; {js|Jean-Baptiste|js}
     ; {js|Jean|js}
     ; {js|Jeremy|js}
     ; {js|Jerome|js}
     ; {js|Jimmy|js}
     ; {js|Jonathan|js}
     ; {js|Jordan|js}
     ; {js|Jules|js}
     ; {js|Julien|js}
     ; {js|Kevin|js}
     ; {js|Louis|js}
     ; {js|Loïc|js}
     ; {js|Lucas|js}
     ; {js|Ludovic|js}
     ; {js|Léo|js}
     ; {js|Marc|js}
     ; {js|Martin|js}
     ; {js|Mathieu|js}
     ; {js|Matthieu|js}
     ; {js|Maxence|js}
     ; {js|Maxime|js}
     ; {js|Mehdi|js}
     ; {js|Mickael|js}
     ; {js|Mohamed|js}
     ; {js|Morgan|js}
     ; {js|Nathan|js}
     ; {js|Nicolas|js}
     ; {js|Olivier|js}
     ; {js|Paul|js}
     ; {js|Pierre|js}
     ; {js|Quentin|js}
     ; {js|Raphaël|js}
     ; {js|Robin|js}
     ; {js|Romain|js}
     ; {js|Rémi|js}
     ; {js|Rémy|js}
     ; {js|Samuel|js}
     ; {js|Simon|js}
     ; {js|Steven|js}
     ; {js|Stéphane|js}
     ; {js|Sylvain|js}
     ; {js|Sébastien|js}
     ; {js|Tanguy|js}
     ; {js|Thibault|js}
     ; {js|Thibaut|js}
     ; {js|Thomas|js}
     ; {js|Théo|js}
     ; {js|Tom|js}
     ; {js|Tony|js}
     ; {js|Tristan|js}
     ; {js|Valentin|js}
     ; {js|Victor|js}
     ; {js|Vincent|js}
     ; {js|William|js}
     ; {js|Yanis|js}
     ; {js|Yann|js}
     ; {js|Yoann|js} |]

  let elements =
    Js.Array2.concatMany [||]
      [|german_females; german_males; french_females; french_males|]
end

include Random_collection.Make (P)
